# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-MirapointAdmin
version:      3.04
version_from: lib/Net/MirapointAdmin.pm
installdirs:  site
requires:
    IO::Socket:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
